Milestone 5 - Refactor OOP
mukhammadrizooff/OOP-school-library pull request #6
Opened 2022-04-25 21:26 UTC by mukhammadrizooff

# In this branch we implement:
- Refactoring create method files.
- Create separate classes for `app.rb` functions.
- We attention to the "Single-responsibility Principle" 
- We tested all functions and it's working well.
<img width="100%" src="https://media4.giphy.com/media/oV5jZJS2i5Nep7MTNF/giphy.gif"/>

2022-04-25 21:44 UTC, eri8-9 requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

![almost there](https://media.giphy.com/media/7JsChhLbpj0rJtzimC/giphy.gif)

## Suggested changes

- [ ] Seems that the app don't show the rentals after click on the option list all rentals. Possibly because a problem with the refactoring. Please take a look on that. 👍🏼
![Screen Shot 2022-04-25 at 16 36 28](https://user-images.githubusercontent.com/67211919/165179540-af93c65d-c77a-4694-be1f-3653ac93102d.png)

_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-26 01:06 UTC, mukhammadrizooff commented
### **We are fixing the problem, thank you in advance!**
![2022-04-26_06-02-44](https://user-images.githubusercontent.com/63915024/165198633-89770aff-8fe8-4b53-9455-c05259b73870.png)

2022-04-26 01:33 UTC, medaminedev66 approved these changes
## Hi @mukhammadrizooff, @danielufeli and @denscholar, 

# Highlights
- The school library app works as expected. Great job 👍
# Status: Approved ✔️
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚢
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 01:33 UTC, medaminedev66 commented on rental.rb
>      @date = date
[OPTIONAL] It would be better to avoid errors in your app and improve the user experience as much as you can. I would recommend showing a message ex: "The person with the number "ex: 3" doesn't exist" if the user chooses a wrong number or a number that does not exist so the user has a second chance to create another rental instead of exiting the app. 

<img width="737" alt="image" src="https://user-images.githubusercontent.com/77190203/165201210-979ede63-8247-41b4-a513-3fcb9dae4332.png">

2022-04-26 01:45 UTC, merged